# Dependencies
markdown:               redcarpet

redcarpet:
    extensions:         ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "subscript"]

highlighter:            rouge

# Permalinks
permalink:              pretty

# Setup
title:                  Notes
baseurl:                /notes

author:
    name:               "Dhananjoy Biswas"
    email:              "ebappa1971@gmail.com"

github:
    repo:               https://github.com/Corei13/notes

sections:         ["Programming", "Mathematics", "Machine Learning"]
